chingu-voyages/v37-bears-team-14

- backend/nodemon.json
- backend/package.json
- backend/src/auth/github.test.ts
- backend/src/auth/github.ts
- backend/src/auth/passport.ts
- backend/src/config.test.ts
- backend/src/config.ts
- backend/src/index.ts
- backend/src/logger.ts
- backend/src/models/User.ts
- backend/src/routes/auth.ts
- backend/yarn.lock
- docs/DESIGN.md
- frontend/package.json
- frontend/src/setupProxy.js
- frontend/yarn.lock
1. Add new configs: https://discord.com/channels/330284646283608064/939665645107282010/940802454881194046
2. Run `yarn dev` 
3. Navigate to `localhost:3000/auth/github`
4. Check that you can authenticate with github and are redirected to "/"
Closes #23
> Implement github auth for User

- backend/src/auth/github.ts
- backend/src/auth/passport.ts
- backend/src/controllers/UserController.test.ts
- backend/src/controllers/UserController.ts
- backend/src/index.ts
Also fixes passport initialize/session setup.
1. Run the app
2. Log in with Github account
3. Assert that User record contains non-null "username"
Closes #26
> Default username if not exists in User

- backend/src/routes/auth.ts
- frontend/src/Navbar.tsx
added links to sign in and sign out auth api endpoints to the navbar. Github sign in and out appears to be working from the navbar.
> add login and logout functionality to navbar

- backend/src/controllers/ProjectController.ts
- backend/src/controllers/UserController.ts
- backend/src/controllers/errors/FieldExistsError.ts
- backend/src/controllers/errors/UnauthorizedError.ts
- backend/src/controllers/errors/UnexpectedError.ts
- backend/src/models/Member.ts
- backend/src/models/Project.ts
- backend/src/routes/api.ts
- backend/src/routes/projectRouter.ts
- backend/src/types/express.ts
- docs/DESIGN.md
New Endpoints
```
POST /api/v1/projects
POST /api/v1/projects/{id}
GET /api/v1/projects/{id}
GET /api/v1/project_lookup/{name}
```
1. Run backend
2. Log in and authenticate to app
3. Try the various endpoints and assert the success responses are as expected
4. Try the various endpoints and assert the error responses are as expected
```
POST /api/v1/projects
{
"name": "hello",
"description": "world",
"techs": ["6209ee36a00bb00582784da9"]
}
Success Example
Response 200:
{
"createdAt" : "2022-02-14T06:49:47.365Z",
"id" : "6209fb8bdbda9e32a9740bf4",
"name" : "hello",
"description": "world",
"techs" : [
{
"createdAt" : "2022-02-14T05:52:54.098Z",
"description" : "Automated service discovery and registration framework",
"id" : "6209ee36a00bb00582784da9",
"imageUrl" : null,
"name" : …
```
> Implement project API

- backend/src/controllers/ProjectController.ts
- frontend/src/components/projects/ProjectPreviewSearch.tsx
- frontend/src/components/projects/ProjectSearch.tsx
- frontend/src/shared/Interfaces.ts
Project search results weren't linking to project pages.
> fix project page link from search results

- backend/src/index.ts
- Adds /ping endpoint: response 200, no body
- run app
- call /ping path, should get 200 response
`curl -I localhost:8080/ping`
> Add /ping endpoint

- backend/src/controllers/ProjectController.ts
- frontend/src/components/projects/ProjectPreview.tsx
- frontend/src/components/projects/ProjectPreviewSearch.tsx
- frontend/src/components/projects/ProjectSearch.tsx
- frontend/src/shared/Interfaces.ts
> Add members to frontend

- frontend/src/components/formatting/Preview.tsx
- frontend/src/components/project_page/components/ProjectPageMarkdown.tsx
- frontend/src/index.css
Fixes ul and ol styling outside of ReactMarkdown components
> fix ul and ol styling

- frontend/src/components/project_page/components/ProjectTabs.tsx
> Fix ProjectTabs spacing

- backend/src/controllers/ProjectController.ts
- backend/src/routes/projectRouter.ts
- frontend/src/components/project_page/pages/ProjectLandingPage/index.tsx
closes issue #97 
to test do a get request to http://localhost:8080/api/v1/user_projects?user=62041c51a00bb005822d8388
or replace user with your userId.
Check that you are a member of all projects returned
> Endpoint for getting current user's projects

- backend/src/controllers/ProjectController.ts
- backend/src/controllers/projects/searchHelpers.ts
- backend/src/models/Project.ts
- backend/src/routes/projectRouter.ts
- frontend/src/components/icons/StarIcon.tsx
- frontend/src/components/project_page/pages/ProjectLandingPage/components/StarButton.tsx
- frontend/src/components/project_page/pages/ProjectLandingPage/index.tsx
- frontend/src/components/projects/ProjectPreview.tsx
- frontend/src/components/projects/Projects.tsx
> Project stars 2

- frontend/src/components/project_page/components/ProjectSettingsForm.tsx
- frontend/src/components/projects/NewProjectForm.tsx
- frontend/src/shared/schemas/project.schema.ts
- Make new project form and project settings use the same field validation schema
> Share field validation schema for project create/update

- README.md
> Add TOC and values to README

- backend/src/controllers/NotificationController.ts
- backend/src/middleware/isAdmin.ts
- backend/src/models/Notification.ts
- backend/src/routes/api.ts
- backend/src/routes/notificationRouter.ts
- backend/src/services/NotificationService.ts
- frontend/src/App.tsx
- frontend/src/Navbar.tsx
- frontend/src/components/admin/notifications/NotificationTestPage.tsx
- frontend/src/components/icons/BellIcon.tsx
- frontend/src/components/notifications_page/NotificationListPage.tsx
- frontend/src/components/notifications_page/useNotifications.tsx
- frontend/src/components/project_page/pages/ProjectLandingPage/components/ProjectEventPreview/index.tsx
- frontend/src/index.tsx
- frontend/src/shared/NotificationInterfaces.ts
- Adds Notification model, controller, and service
Note: Controller is responsible for API routes, Service is intended to be called from other Controllers
- Run app
- Set user to be isAdmin=true in database
- Go to `/admin/notifications`
- Send a test notification
- Go to `/notifications` and reload the page
- Check that the test notification shows up
Note: getting the latest notification requires refreshing the page, but in the future I plan to add a push mechanism (either websocket or server-sent event)
Closes #130
> Add Notification model and notification tester

- backend/package.json
- package.json
See: https://github.com/chingu-voyages/v37-bears-team-14/pull/new/fix/package-json-required-fields
> Add required name/version fields to package.json files

- backend/src/config.ts
- backend/src/controllers/ApplicationController.ts
- backend/src/controllers/ProjectController.ts
- backend/src/controllers/projects/searchHelpers.ts
- backend/src/messaging/NotificationService.ts
- backend/src/messaging/setup.ts
- backend/src/models/Member.ts
- frontend/src/App.tsx
- frontend/src/components/navbar/Navbar.tsx
- frontend/src/components/navbar/NotificationIcon.tsx
- frontend/src/components/notifications_page/NotificationListPage.tsx
- Adds `application_created` notification
- Adds notification bubble to frontend and exposes to all users
- Run app
- Test that notifications show up and link to applications correctly
- Submit an application
Closes #139 
Closes #140
> Add Notification Bubble and Application-Created notification

- backend/package.json
- backend/src/controllers/ProjectController.ts
- backend/src/models/Comment.ts
- backend/src/models/User.ts
- backend/src/routes/projectRouter.ts
- backend/yarn.lock
- frontend/src/components/comments/CommentForm.tsx
- frontend/src/components/comments/NewComment.tsx
- frontend/src/components/controls/CommentLink.tsx
- frontend/src/components/controls/DeleteLink.tsx
- frontend/src/components/icons/CommentIcon.tsx
- frontend/src/components/project_page/pages/ProjectLandingPage/index.tsx
- frontend/src/index.css
- frontend/src/shared/Interfaces.ts
- frontend/tailwind.config.js
Closes issue #117
- Go to a project, sign in, and add a comment. 
- Reply to that comment. 
- Add other comments as another user and test that the ability to delete and edit comments is only available to the user who created the comment. 
- Test that all comments are visible to signed in and non signed in users. Test edit and delete functionality.
> Add comments section to projects

- backend/src/routes/api.ts
- frontend/src/components/user_page/components/UpdateUserForm.tsx
Making it so that only alphanumeric values are allowed when updating the user's username.
> Fixed username update to only accept alphanumeric values.

- frontend/src/components/user_page/components/UpdateUserForm.tsx
> Add small layout change to UpdateUserForm.tsx

- backend/package.json
- backend/src/controllers/ProjectController.ts
- backend/src/models/Comment.ts
- backend/yarn.lock
- frontend/src/components/comments/CommentForm.tsx
- frontend/src/components/comments/NewComment.tsx
- frontend/src/shared/Interfaces.ts
To Test:
- Create a comment
- Create a reply to that comment
- Delete the root comment
- Check that the text of the root comment appears as "*Comment Deleted*" and that replies still exist
- Test comment creation, edit and delete
> Update Comment delete functionality
